defaults: &defaults
  email: example_user@example.com
  addthis_twitter_user: example_user@example.com
  addthis_user: example_user
  google_analytics_code: 123
  google_analytics_cookie_path:  ""
  src_maps_dir: "/public/mapimages/src/"
  dst_maps_dir: "/public/mapimages/dst/"
  yahoo_app_id: "ascas"
  host: "localhost:3000"
  mailer_sender: "robot@localhost"

development:
  <<: *defaults

test:
  <<: *defaults
  email: test_user@example.com

production:
  <<: *defaults
  email: production_user@example.com
