defaults: &defaults
  email: example_user@example.com
  addthis_twitter_user: example_user@example.com
  addthis_user: example_user
  google_analytics_code: 123
  google_analytics_cookie_path:  ""
  src_map_dir: "/public/mapimages/src/"
  dst_map_dir: "/public/mapimages/dst/"
  yahoo_app_id: "ascas"

development:
  <<: *defaults

test:
  <<: *defaults
  email: test_user@example.com

production:
  <<: *defaults
  email: production_user@example.com
